spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/english_lessons_course_project"
    username: "root"
    password: "1D4fkS"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    database: "postgresql"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

  sql:
    init:
      mode: "embedded"
      schema-locations: "classpath*:db/migration/V1__init_db.sql"
  flyway:
      baseline-on-migrate: true
      baseline-version: 0